[package]
name = "detours-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.55.1"
cc = { git = "https://github.com/SpiralP/cc-rs.git" }

[dev-dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi"] }
